#!/usr/bin/python -u
import digitalio
import board
import time
from board import *
import glob
import adafruit_dht
import RPi.GPIO as GPIO
import os
import datetime

## A - LIÐUR
## Kveikjum á viftu

# Configuration
FAN_GPIO_PIN = 20
RELAY_FAN_GPIO_PIN = 26 # BCM pin used to turn RELAY for FAN ON/OFF
RELAY_HEATER_FAN_GPIO_PIN = 16
##PWM_duty_cycle = 10
PWM_FREQ = 125        # [Hz] 25kHz for PWM control


PWM_OFF = 0             # the PWM_duty_cycle 0%
PWM_MAX = 100           # the PWM_duty_cycle 100%
dutycyclegildi = [10, 90]



################################################
try:
	GPIO.setwarnings(False)
	GPIO.setmode(GPIO.BCM)

# PWM used to control the fan's speed
	GPIO.setup(RELAY_FAN_GPIO_PIN, GPIO.OUT, initial=GPIO.HIGH)
# tachometer - from a hall sensor located in the fan
	GPIO.setup(RELAY_HEATER_FAN_GPIO_PIN, GPIO.OUT, initial=GPIO.HIGH)

	GPIO.output(RELAY_FAN_GPIO_PIN,GPIO.LOW) # Turn the FAN ON
	print("FAN IS ON")
	time.sleep(5)

	GPIO.output(RELAY_HEATER_FAN_GPIO_PIN, GPIO.LOW)
	print("HEATER ON")
except KeyboardInterrupt:
		GPIO.cleanup() # resets all GPIO ports used by this function


# Set fan speed
def setFanSpeed(PWM_duty_cycle):
	fan.start(PWM_duty_cycle)
	return()

try:
	GPIO.setwarnings(False)
	GPIO.setup(FAN_GPIO_PIN,GPIO.OUT, initial = GPIO.LOW)
	fan = GPIO.PWM(FAN_GPIO_PIN, PWM_FREQ)
	setFanSpeed(PWM_OFF)

#### Setjum Duty Cycle ####

	for i in dutycyclegildi:
		setFanSpeed(i)
		time.sleep(30)
		print("Duty cycle: " + str(i))

###### Hitanemi ######

#ds18b20read hitaneminn

		base_dir = '/sys/bus/w1/devices/'
		device_folder = glob.glob(base_dir + '28*')[0]
		device_file = device_folder + '/temperature'

#Mælum hitastig
		def read_temp_raw():
			temp_string = read_temp_raw()
			temp_c = float(temp_string) / 1000.0
			gildi10 = []
			gildi90 = []
			while (teljari < 11):
				print(temp_c)
				if i == 0:
					gildi10.append(temp_c)
				else:
					gildi90.append(temp_c)
					time.sleep(10)
					teljari = teljari + 1

			medaltal10 = sum(gildi10)/10
			medaltal90 = sum(gildi90)/10

			print(medaltal10)
			print(medaltal90)

	i += 1
except KeyboardInterrupt:
	setFanSpeed(FAN_OFF)

	## finna meðaltal af mælingunum tíu
